import type { Product } from '@/types';

/**
 * Storage for the admin portal's product drafts. This site is statically
 * generated with no server-side storage, so "editing products" here means
 * editing a draft that lives in the admin's own browser — not a shared
 * database. See lib/products.ts's own header and the admin portal for the
 * full picture: this is the draft; that file is what actually ships to
 * real visitors, until someone exports and redeploys.
 */
const ADMIN_PRODUCTS_KEY = 'ambalathara-admin-products-v1';

/** Null when nothing has been saved yet, or the stored value is unparseable. */
export function loadAdminProducts(): Product[] | null {
  if (typeof window === 'undefined') return null;

  try {
    const raw = window.localStorage.getItem(ADMIN_PRODUCTS_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as Product[]) : null;
  } catch {
    return null;
  }
}

export function saveAdminProducts(products: Product[]): void {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(ADMIN_PRODUCTS_KEY, JSON.stringify(products));
  // So other tabs (e.g. the live site open alongside /admin) pick up the
  // change immediately — see useAdminProducts' storage listener. The
  // native `storage` event only fires in *other* tabs, not this one, so
  // this dispatch is what lets a same-tab admin preview stay in sync too.
  window.dispatchEvent(new Event('admin-products-updated'));
}

/** Discards the local draft, reverting the site back to lib/products.ts's defaults. */
export function clearAdminProducts(): void {
  if (typeof window === 'undefined') return;
  window.localStorage.removeItem(ADMIN_PRODUCTS_KEY);
  window.dispatchEvent(new Event('admin-products-updated'));
}

/**
 * Builds the full replacement source for lib/products.ts. Plain
 * `JSON.stringify` output is already valid TS object-literal syntax (JSON
 * strings are a subset of JS string syntax, JSON's double-quoted keys are
 * valid as object keys too) — no need for a hand-rolled pretty-printer.
 * Cosmetically double-quoted rather than the hand-written file's single
 * quotes; that's an expected, harmless diff once pasted in.
 */
export function generateProductsFileContent(products: Product[]): string {
  return `import type { Product } from '@/types';

/**
 * The product catalog — the one place to edit names, descriptions and
 * items. Generated by the admin portal (/admin) — edit there and
 * re-export, rather than hand-editing this array, so the two never drift.
 */
export const PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};
`;
}

/** Long edge cap for uploaded product photos, before they're stored as data URLs. */
const MAX_IMAGE_DIMENSION = 1000;
const IMAGE_QUALITY = 0.82;

/**
 * Resizes an uploaded image client-side (canvas) and returns it as a JPEG
 * data URL, so it can sit directly in a Product's `image` field with no
 * upload endpoint at all. Capped at MAX_IMAGE_DIMENSION on the long edge —
 * keeps localStorage comfortably within its per-origin quota (a handful of
 * MB in most browsers) and keeps the exported lib/products.ts a reasonable
 * size, rather than storing multi-megabyte originals verbatim.
 */
export function resizeImageFile(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(reader.error ?? new Error('Could not read file'));
    reader.onload = () => {
      const img = new Image();
      img.onerror = () => reject(new Error('Could not decode image'));
      img.onload = () => {
        const scale = Math.min(1, MAX_IMAGE_DIMENSION / Math.max(img.width, img.height));
        const width = Math.round(img.width * scale);
        const height = Math.round(img.height * scale);

        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          reject(new Error('Canvas unavailable'));
          return;
        }
        ctx.drawImage(img, 0, 0, width, height);
        resolve(canvas.toDataURL('image/jpeg', IMAGE_QUALITY));
      };
      img.src = reader.result as string;
    };
    reader.readAsDataURL(file);
  });
}
